# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

exceptions:
  InstanceOfCheckForException:
    active: true
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  NotImplementedDeclaration:
    active: true
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
    ignoredExceptionTypes:
      - InterruptedException
      - MalformedURLException
      - NumberFormatException
      - ParseException
    allowedExceptionNameRegex: _|(ignore|expected).*

formatting:
  autoCorrect: true
  AnnotationOnSeparateLine:
    active: true
  AnnotationSpacing:
    active: true
  ArgumentListWrapping:
    active: true
    maxLineLength: 140
  ClassName:
    active: true
  EnumWrapping:
    active: true
  FunctionName:
    active: true
  FunctionSignature:
    active: true
    maxLineLength: 140
    indentSize: 2
  Indentation:
    active: true
    indentSize: 2
  MaximumLineLength:
    active: true
    maxLineLength: 140
  MultiLineIfElse:
    active: true
  NoBlankLineInList:
    active: true
  NoEmptyFirstLineInMethodBlock:
    active: true
  NoMultipleSpaces:
    active: false
  NoWildcardImports:
    active: false
  ParameterListWrapping:
    active: true
    indentSize: 2
    maxLineLength: 140
  ParameterWrapping:
    active: true
    maxLineLength: 140

performance:
  CouldBeSequence:
    active: true
  SpreadOperator:
    active: false
  UnnecessaryPartOfBinaryExpression:
    active: true

style:
  AlsoCouldBeApply:
    active: true
  BracesOnIfStatements:
    active: true
    singleLine: 'necessary'
    multiLine: 'consistent'
  BracesOnWhenStatements:
    active: true
    singleLine: 'necessary'
    multiLine: 'necessary'
  CanBeNonNullable:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: false
  DataClassShouldBeImmutable:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  DoubleNegativeLambda:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExpressionBodySyntax:
    active: true
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 3
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreRanges: true
    ignoreEnums: true
    excludes:
      - '**/*Theme*'
      - '**/*Painter*'
      - '**/build.gradle.kts'
  MandatoryBracesLoops:
    active: true
  MaxChainedCallsOnSameLine:
    active: true
    maxChainedCalls: 2
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludeCommentStatements: true
    excludeRawStrings: true
  MultilineLambdaItParameter:
    active: true
  NoTabs:
    active: true
  ObjectLiteralToLambda:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantExplicitType:
    active: true
  RedundantHigherOrderMapUsage:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    max: 6
    excludeGuardClauses: true
  SerialVersionUIDInSerializableClass:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  StringShouldBeRawString:
    active: true
  TrailingWhitespace:
    active: true
  TrimMultilineRawString:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryInnerClass:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseAnyOrNoneInsteadOfFind:
    active: true
  UseDataClass:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseSumOfInsteadOfFlatMapSize:
    active: true
  WildcardImport:
    active: false

comments:
  AbsentOrWrongFileLicense:
    active: false
  DeprecatedBlockTag:
    active: true
  KDocReferencesNonPublicProperty:
    active: true
  OutdatedDocumentation:
    active: true
    matchTypeParameters: true
    matchDeclarationsOrder: true
  UndocumentedPublicClass:
    active: false
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/*Bundle*'
      - '**/actions/**'
  UndocumentedPublicFunction:
    active: false
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/*Bundle*'
      - '**/actions/**'

complexity:
  LargeClass:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NamedArguments:
    active: true
  NestedScopeFunctions:
    active: true
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: false
    threshold: 3
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: $^
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/build.gradle.kts'
  TooManyFunctions:
    active: false

naming:
  FunctionMaxLength:
    active: true
    maximumFunctionNameLength: 36
    excludes:
      - '**/*Page*'
      - '**/*Settings*'
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 2
  InvalidPackageDeclaration:
    active: true
  LambdaParameterNaming:
    active: true
  NoNameShadowing:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  VariableMaxLength:
    active: true


potential-bugs:
  CastNullableToNonNullableType:
    active: true
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  HasPlatformType:
    active: true
  ImplicitUnitReturnType:
    active: true
  MissingPackageDeclaration:
    active: true
    excludes:
      - '**/*.kts'
  NullableToStringCall:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
